### PR TITLE
Update to latest php 7.1.1

### PR DESCRIPTION
**Pull request by StalkAlex**

### CODE REVIEW

**Comment by schmunk42** [comment]
Is there a special reason for pinning down the version to 7.1.1 - I'd rather stay on the 7.1 "branch", which usually pretty safe in PHP.

**Comment by StalkAlex** [comment]
Nothing special about it, minor changes, improvements, bugfixes and so on. I usually stick to the latest stable version for php. So it more stable I think. If you decided so it wouldn't be a big problem.

**Comment by schmunk42** [comment]
`php:7.1` should be the latest stable 7.1.x - let me know in case you need a newer version, I'll just trigger a build if needed.

**Comment by StalkAlex** [comment]
Hmm, don't understand a little bit. I needed more newer version, that's why I made this PR.

**Comment by schmunk42** [comment]
I've updated the base-images, see also 
- https://hub.docker.com/r/dmstr/php-yii2/tags/ 
- https://github.com/dmstr/docker-php-yii2#supported-tags-and-respective-dockerfile-links

**Comment by StalkAlex** [comment]
Aha, I see. Sorry I wrote not clearly first time. I meant to make just another extra tag for php 7.1.1 or beta or similar. I wasn't talking about your container, when said 'last stable' I've talked about php last stable release - 7.1.1

**Comment by schmunk42** [comment]
The image is based on 7.1.1 so you're fine I think. 

The change from 1.9 to 2.0-beta is not that big, it should be fully compatible. We're just versioning cautiously :)

**Comment by StalkAlex** [comment]
Okay, thanks:)  really like your work.

**Comment by schmunk42** [comment]
Thank you :)

**Pull request closed without merging**
